---
title: "Tutorial: Bayesian Testing of Central Structures in Psychological Networks"
author: "Josue Rodriguez"
date: "2020-05-08"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
draft: false
bibliography: [C:\\Users\\josue\\Box\\Papers\\02-formalizing-expectations\\references.bib]
csl: apa.csl
---



<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>This tutorial demonstrates how to use networks (specifically Gaussian graphical models or GGMs) to</p>
<ol style="list-style-type: decimal">
<li>Generate hypotheses</li>
<li>Perform confirmatory tests on the generated hypotheses</li>
</ol>
<!-- In psychology, network models are almost never used to generate hypotheses. This is puzzling because one of the original reasons researchers began using them was exactly this. Networks are also thought of as highly exploratory tools, despite their potential for confirmatory tests.  -->
<p>Network theory has emerged as a popular framework for conceptualizing psychological constructs and mental disorders. Initially, network analysis was motivated in part by the thought that it can be used for hypothesis generation. Although the customary approach for network modeling is inherently exploratory, we argue that there is untapped potential for confirmatory hypothesis testing. These ideas are expanded upon in our recent paper, “On Formalizing Theoretical Expectations: Bayesian Testing of Central Structures in Pyschological Networks”, where we merge exploratory and confirmatory hypotheses into a cohesive framework based on Bayesian hypothesis testing. You can find the preprint <a href="https://psyarxiv.com/zw7pf/">here</a>.</p>
<p>In what follows, I will describe how you can use <code>R</code> to perform confirmatory hypothesis tests based on initial, exploratory hypotheses with GGMs. For clarity, some code chunks have been omitted, but the full code to reproduce this document can be obtained on the <a href="https://osf.io/bh783">Open Science Framework</a> or <a href="https://github.com/josue-rodriguez/formalizing-expectations">GitHub</a>.</p>
</div>
<div id="examples" class="section level1">
<h1>Examples</h1>
<div id="ptsd-network" class="section level2">
<h2>PTSD Network</h2>
<p>To begin we need several packages:</p>
<ul>
<li><code>BGGM</code>: to conduct exploratory and confirmatory analyses with GGMs</li>
<li><code>MASS</code>: to generate data from covariance matrices</li>
<li><code>networktools</code>: to calculate bridge centrality statistics</li>
</ul>
<pre class="r"><code># Uncomment and run  if missing packages

# for latest version of BGGM
# remotes::install_github(&#39;donaldrwilliams/BGGM&#39;) 

# packages &lt;- c(&quot;MASS&quot;, &quot;networktools&quot;)
# if (!packages %in% installed.packages()) install.packages(packages)</code></pre>
<pre class="r"><code>library(MASS)
library(networktools)
library(BGGM)</code></pre>
<p>The first dataset contains measurements on 16 PTSD symptoms in 3 communities, “Re-experiencing”, “Avoidance”, and “Arousal” <span class="citation">(Sample 4 in Fried et al., <a href="#ref-friedReplicability2018a" role="doc-biblioref">2018</a>)</span>. Only the correlations matrices are available so we have to generate the data using <code>MASS::mvrnorm</code> with <code>empirical = TRUE</code>. This ensures that the generated data have the exact covariance structure we give it. The correlation matrix, <code>ptsd_cor4</code>, is loaded with <code>BGGM</code>.</p>
<pre class="r"><code>set.seed(1812)

# data for exploratory analyses
explore_ptsd &lt;- mvrnorm(n = 965, 
                        mu = rep(0, 16), 
                        Sigma = ptsd_cor4, 
                        empirical = TRUE)
colnames(explore_ptsd) &lt;- node_names</code></pre>
<div id="exploratory-analysis" class="section level3">
<h3>Exploratory analysis</h3>
<div id="estimate-graph" class="section level4">
<h4>Estimate graph</h4>
<p>The approach begins by estimating an exploratory network. With <code>BGGM</code>, this requires calling the <code>explore</code> function to obtain and sample the posterior distribution. These results are saved in <code>explore_network</code>. The <code>select</code> function takes the results from an <code>explore</code> call, and is used to determine the edge set for <span class="math inline">\(\mathbf{A}^{CD}\)</span> and <span class="math inline">\(\mathbf{A}^{CI}\)</span> — the conditional (in)dependence structures. We used <code>type = "continuous"</code> as the data we generated are multivariate normal, but the latest version <code>BGGM</code> can also handle ordinary and binary data.</p>
<p>Note that <code>alternative = "exhaustive"</code> is used for determining the edge set. This returns three adjacency matrices. One for positive, negative, and null edges. In the paper, we focus on positive and null relations. The former is due to the expectation that edges in psychological networks are expected to be positive (i.e., a positive manifold).</p>
<pre class="r"><code># sample posterior distribution
explore_network &lt;- explore(explore_ptsd, 
                           type = &quot;continuous&quot;,
                           iter = 5000)

# determine edge set
selected_network &lt;- select(explore_network, 
                           alternative = &quot;exhaustive&quot;, 
                           bf_cut = 3)</code></pre>
</div>
<div id="bridge-centrality" class="section level4">
<h4>Bridge Centrality</h4>
<p>The next step is to calculate bridge strength using the <code>networktools</code> package. This is similar to node strength, in that, for a given node, it is the sum of the absolute values of its edges. However, bridge strength only takes into account edges that connect to different communities, or clusters. Thus, it is a measure of inter-community connectivity, and can be used to identify central structures in a network.</p>
<pre class="r"><code># retain positive partial correlations from selected network
partial_cors &lt;- selected_network$pcor_mat * selected_network$pos_mat

# rename columns with node names
dimnames(partial_cors) &lt;- list(node_names, node_names)

# calculate bridge strength. comms is a vector specifying 
# the community for each node
bridge_strengths &lt;- bridge(partial_cors, communities = comms)$`Bridge Strength`

# we use the top 10% in bridge strength as bridge nodes
bridge_strength_cutoff &lt;- quantile(bridge_strengths, 0.9)
bridge_strengths[bridge_strengths &gt; bridge_strength_cutoff]</code></pre>
<pre><code>##    B4    D1 
## 0.532 0.657</code></pre>
<p>Notice that the partial correlation matrix was multiplied by adjacency matrix for partial correlations (<code>selected_network$pos_mat</code>). This ensures we are only focusing on positive associations.</p>
<p>Calculating bridge strength indicates that nodes B4 and D1 are the top bridge nodes.</p>
</div>
<div id="plot-bridges" class="section level4">
<h4>Plot bridges</h4>
<p>A key idea in our paper was that highlighting and “zooming” in on central structures allows researchers to easily formulate hypotheses. For example, we plotted the neighborhood of bridge relations for nodes D1 and B4.</p>
<p><img src="/post/tutorial-bayesian-testing_files/figure-html/plot-ptsd-bridges-1.png" width="672" /><img src="/post/tutorial-bayesian-testing_files/figure-html/plot-ptsd-bridges-2.png" width="672" /></p>
</div>
</div>
<div id="confirmatory-analysis" class="section level3">
<h3>Confirmatory analysis</h3>
<p>With the central structures identified and plotted, we can then move on to formulating and testing hypotheses.</p>
<p>For this confirmatory analysis, data were generated from another correlation matrix <span class="citation">(Sample 3 in Fried et al., <a href="#ref-friedReplicability2018a" role="doc-biblioref">2018</a>)</span>. This was done to test our hypotheses on a different dataset than the one used for exploratory analysis.</p>
<pre class="r"><code>set.seed(1)

confirm_ptsd &lt;- mvrnorm(n = 926, 
                        mu = rep(0, 16), 
                        Sigma = ptsd_cor3, 
                        empirical = TRUE)

colnames(confirm_ptsd) &lt;- node_names</code></pre>
<div id="varying-degrees-of-replication" class="section level4">
<h4>Varying degrees of replication</h4>
<p>We first focus on node B4 and test the following hypotheses
<span class="math display">\[\begin{align}
    \mathcal{H}_1&amp;: (\rho_{B4-C1}, \rho_{B4-C7}, \rho_{B4-D3},  \rho_{B4-D4}) &gt; 0 \\ \nonumber
    \mathcal{H}_2&amp;: \rho_{B4-C1} &gt; (\rho_{B4-C7}, \rho_{B4-D3}, \rho_{B4-D4}) &gt; 0 \\ \nonumber
    \mathcal{H}_3 &amp;: ``\text{not}\; \mathcal{H}_1 \; \text{or}\; \mathcal{H}_2  \text{.&#39;&#39;}
\end{align}\]</span></p>
<p>Above, <span class="math inline">\(\mathcal{H}_1\)</span> is testing for replication of all edges but is otherwise agnostic towards the interplay among bridge relations. <span class="math inline">\(\mathcal{H}_2\)</span> then provides a refined view into the bridge neighborhood by testing an additional constraint that the strongest edge replicated. That is, all of the bridge relations <em>and</em> the strongest edge re-emerged in an independent dataset. Furthermore, <span class="math inline">\(\mathcal{H}_1\)</span> and <span class="math inline">\(\mathcal{H}_2\)</span> both reflect a positive manifold. We also included <span class="math inline">\(\mathcal{H}_3\)</span> which accounts for structures that are not <span class="math inline">\(\mathcal{H}_1\)</span> or <span class="math inline">\(\mathcal{H}_2\)</span>.</p>
<p>To test these hypotheses, we can write them out in a single string and use the <code>confirm</code> function. Note that hypotheses are separated by a semicolon, and that partial correlations are denoted as <code>node1 -- node2</code>. The output is obtained by simply printing out the results of <code>confirm</code>.</p>
<pre class="r"><code>hyp_var_rep &lt;- c(&quot;(B4--C1, B4--C7, B4--D3, B4--D4) &gt; 0;
                   B4--C1 &gt; (B4--C7, B4--D3, B4--D4) &gt; 0&quot;)

confirm_var_rep &lt;- confirm(confirm_ptsd,
                           hyp_var_rep,
                           iter = 50000)
confirm_var_rep</code></pre>
<pre><code>## BGGM: Bayesian Gaussian Graphical Models 
## Type: continuous 
## --- 
## Posterior Samples: 50000 
## Observations (n): 926 
## Variables (p): 16 
## Delta: 15 
## --- 
## Call:
## confirm(Y = confirm_ptsd, hypothesis = hyp_var_rep, iter = 50000)
## --- 
## Hypotheses: 
## 
## H1: (B4--C1,B4--C7,B4--D3,B4--D4)&gt;0
## H2: 
## B4--C1&gt;(B4--C7,B4--D3,B4--D4)&gt;0
## H3: complement
## --- 
## Posterior prob: 
## 
## p(H1|data) = 0.197
## p(H2|data) = 0.797
## p(H3|data) = 0.006
## --- 
## Bayes factor matrix: 
##       H1    H2      H3
## H1 1.000 0.247  33.401
## H2 4.054 1.000 135.404
## H3 0.030 0.007   1.000
## --- 
## note: equal hypothesis prior probabilities</code></pre>
<p>The output includes both the posterior probabilities and all of the Bayes factors. The Bayes factors are in reference to the rows relative to the columns. For example the element in the 2nd row and 1st column would be interpreted as <span class="math inline">\(\text{BF}_{21} = 4.05\)</span></p>
<p>In this case, <span class="math inline">\(\mathcal{H}_2\)</span> is the preferred hypothesis, that is, all of the bridge edges and the strongest edge replicated. This gets at an important notion. It is possible to test <em>varying degrees of replication</em>.</p>
<!-- This analysis also indicates that (1) the bridge relations replicated in an independent dataset; and (2) the relation between ``sleep problems'' (node B4) and ``avoidance of thoughts'' (node C1) \emph{could} be the strongest bridge between the Re-experiencing and Avoidance communities. -->
</div>
</div>
</div>
<div id="comorbidity-network" class="section level2">
<h2>Comorbidity Network</h2>
<p>We also examined a comorbity network containing 16 symptoms of anxiety and depression <span class="citation">(Beard et al., <a href="#ref-beardNetwork2016" role="doc-biblioref">2016</a>)</span>, and followed the same steps as above. This dataset is available on the <a href="https://osf.io/wemcg/">OSF</a>. Here, however, we split the data into two because we did not have independent datasets. We formulated hypotheses on one half and tested them on the remaining half.</p>
<div id="exploratory-analysis-1" class="section level3">
<h3>Exploratory analysis</h3>
<pre class="r"><code>set.seed(27)

cov_anxdep &lt;- read.csv(&quot;../05-data/00-cov-anxdep.csv&quot;)[, -1]
sim_anxdep &lt;- MASS::mvrnorm(n = 1029,
                            mu = rep(0, 16), 
                            Sigma = cov_anxdep,
                            empirical = TRUE)

split &lt;- sample(1:1029, size = floor(1029 * .5))
explore_anxdep &lt;- sim_anxdep[split, ]
confirm_anxdep &lt;- sim_anxdep[-split, ]</code></pre>
<pre class="r"><code>explore_network &lt;- explore(explore_anxdep, 
                           type = &quot;continuous&quot;,
                           iter = 5000)

selected_network &lt;- select(explore_network, 
                           alternative = &quot;exhaustive&quot;, 
                           BF_cut = 3)</code></pre>
<div id="bridge-strength" class="section level4">
<h4>Bridge Strength</h4>
<pre class="r"><code>partial_cors &lt;- selected_network$pcor_mat * selected_network$pos_mat

partial_cors &lt;- round(partial_cors, 4)
dimnames(partial_cors) &lt;- list(node_names, node_names)</code></pre>
<pre class="r"><code>bridge_strengths &lt;- bridge(partial_cors, communities = comms)$`Bridge Strength`
bridge_strength_cutoff &lt;- quantile(bridge_strengths, 0.9)
bridge_strengths[bridge_strengths &gt; bridge_strength_cutoff]</code></pre>
<pre><code>##    D6    D8 
## 0.270 0.404</code></pre>
</div>
<div id="plot-bridges-1" class="section level4">
<h4>Plot bridges</h4>
<p><img src="/post/tutorial-bayesian-testing_files/figure-html/plot-anxdep-1.png" width="672" /></p>
</div>
</div>
<div id="confirmatory-analysis-1" class="section level3">
<h3>Confirmatory analysis</h3>
<div id="intra--and-inter-bridge-sets" class="section level4">
<h4>Intra- and Inter-Bridge Sets</h4>
<p>The following hypotheses focus on characterizing bridge sets, or the set of bridge edges belonging to a given symptom. For example, <span class="math inline">\(\mathcal{H}_1\)</span> posits that the bridge set for node D8 is collectively greater than the set for node D6, with the constraint that the edges within the bridge set for D8 are equal to each other. This effectively corresponds to testing whether node D8 has greater bridge strength than node D6. <span class="math inline">\(\mathcal{H}_2\)</span> then refines <span class="math inline">\(\mathcal{H}_1\)</span> by testing an exact order both between and within bridge sets.</p>
<p><span class="math display">\[\begin{align}
\label{eq:intra-inter}
    \mathcal{H}_1 &amp;: \rho_{D8-A5} = \rho_{D8-A7} &gt; (\rho_{D6-A3}, \rho_{D6-A6}) &gt; 0 \\ \nonumber
    \mathcal{H}_2 &amp;: \rho_{D8-A5} &gt; \rho_{D8-A7} &gt; \rho_{D6-A3} &gt; \rho_{D6-A6} &gt; 0 \\ \nonumber
    \mathcal{H}_3 &amp;: ``\text{not}\; \mathcal{H}_1 \; \text{or}\; \mathcal{H}_2 \text{.&#39;&#39;}
\end{align}\]</span></p>
<p>Note that the inclusion of an inequality and equality constraint in a single hypothesis is currently only available on the GitHub version for <code>BGGM</code>.</p>
<pre class="r"><code>intra_inter_hyp &lt;- c(&quot;D8--A5 = D8--A7 &gt; (D6--A3, D6--A6) &gt; 0;
                      D8--A5 &gt; D8--A7 &gt; D6--A3 &gt; D6--A6 &gt; 0&quot;)

confirm_intra_inter &lt;- confirm(Y = confirm_anxdep,
                               hypothesis = intra_inter_hyp,
                               iter = 50000)
confirm_intra_inter </code></pre>
<pre><code>## BGGM: Bayesian Gaussian Graphical Models 
## Type: continuous 
## --- 
## Posterior Samples: 50000 
## Observations (n): 515 
## Variables (p): 16 
## Delta: 15 
## --- 
## Call:
## confirm(Y = confirm_anxdep, hypothesis = intra_inter_hyp, iter = 50000)
## --- 
## Hypotheses: 
## 
## H1: D8--A5=D8--A7&gt;(D6--A3,D6--A6)&gt;0
## H2: 
## D8--A5&gt;D8--A7&gt;D6--A3&gt;D6--A6&gt;0
## H3: complement
## --- 
## Posterior prob: 
## 
## p(H1|data) = 0.037
## p(H2|data) = 0.954
## p(H3|data) = 0.009
## --- 
## Bayes factor matrix: 
##        H1    H2      H3
## H1  1.000 0.039   4.251
## H2 25.905 1.000 110.115
## H3  0.235 0.009   1.000
## --- 
## note: equal hypothesis prior probabilities</code></pre>
<p>The data were more likely under both <span class="math inline">\(\mathcal{H}_1\)</span> (<span class="math inline">\(\text{BF}_{13} = 4.3\)</span>) and <span class="math inline">\(\mathcal{H}_2\)</span> (<span class="math inline">\(\text{BF}_{23} = 110.1\)</span>) than <span class="math inline">\(\mathcal{H}_3\)</span>. Furthermore, there was more evidence supporting the hypothesis testing solely inequality constraints, <span class="math inline">\(\mathcal{H}_2\)</span>, than the one including an equality constraint (<span class="math inline">\(\text{BF}_{21} = 25.9\)</span>). This provides a clear characterization of the the bridge relations at hand — not only did the order of bridge strength replicate, but so did the order of the edges within each bridge set.</p>
</div>
<div id="bridge-set-separation" class="section level4">
<h4>Bridge Set Separation</h4>
<p>We also thought it would be interesting to test whether bridge sets include common elements. That is, whether bridge symptoms connect to the same or different nodes. As can be seen above, the bridge sets for nodes D8 and D6 are mutually exclusive. We can then test, say, whether D8 is conditionally independent from the bridge set for D6 (nodes A3 and A6)</p>
<p><span class="math display">\[\begin{align}
    \mathcal{H}_1 &amp;: (\rho_{D8-A3}, \rho_{D8-A6}) = 0 \\ \nonumber
    \mathcal{H}_2 &amp;: (\rho_{D8-A3}, \rho_{D8-A6})  &gt; 0 \\ \nonumber
    \mathcal{H}_3 &amp;: ``\text{not}\; \mathcal{H}_1 \; \text{or} \; \mathcal{H}_2 \text{.&#39;&#39;}
\end{align}\]</span></p>
<pre class="r"><code>hyp_bridge_sep &lt;- (&quot;(D8--A3, D8--A6) = 0;
                    (D8--A3, D8--A6) &gt; 0&quot;)

confirm_bridge_sep &lt;- confirm(Y = confirm_anxdep,
                              hypothesis = hyp_bridge_sep,
                              iter = 50000)
confirm_bridge_sep</code></pre>
<pre><code>## BGGM: Bayesian Gaussian Graphical Models 
## Type: continuous 
## --- 
## Posterior Samples: 50000 
## Observations (n): 515 
## Variables (p): 16 
## Delta: 15 
## --- 
## Call:
## confirm(Y = confirm_anxdep, hypothesis = hyp_bridge_sep, iter = 50000)
## --- 
## Hypotheses: 
## 
## H1: (D8--A3,D8--A6)=0
## H2: 
## (D8--A3,D8--A6)&gt;0
## H3: complement
## --- 
## Posterior prob: 
## 
## p(H1|data) = 0.307
## p(H2|data) = 0.61
## p(H3|data) = 0.084
## --- 
## Bayes factor matrix: 
##       H1    H2    H3
## H1 1.000 0.503 3.665
## H2 1.989 1.000 7.288
## H3 0.273 0.137 1.000
## --- 
## note: equal hypothesis prior probabilities</code></pre>
<p>Although the data were more likely under <span class="math inline">\(\mathcal{H}_1\)</span> than <span class="math inline">\(\mathcal{H}_3\)</span> (<span class="math inline">\(\text{BF}_{13} = 3.7\)</span>), there was support in favor of <span class="math inline">\(\mathcal{H}_2\)</span> compared to <span class="math inline">\(\mathcal{H}_1\)</span> (<span class="math inline">\(\text{BF}_{21} = 2\)</span>). This analysis suggests it is unlikely that D8 is actually conditionally independent from the bridge set for D6.</p>
</div>
</div>
</div>
</div>
<div id="summary" class="section level1">
<h1>Summary</h1>
<p>In this tutorial, I briefly described a framework to formulate and test hypotheses on psychological networks using <code>BGGM</code>. The idea is to (1) identify central structures on which you can formulate hypotheses in an exploratory analysis and (2) test those hypotheses on independent data. This brings networks to fruition as tools to generate hypotheses and overcomes the idea that they are solely for exploratory purposes.</p>
<p>In writing the above paper, our hope is that researchers can integrate these methods into their work. We believe that conducting confirmatory tests is an important step forward in psychological networks.</p>
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references">
<div id="ref-beardNetwork2016">
<p>Beard, C., Millner, A. J., Forgeard, M. J. C., Fried, E. I., Hsu, K. J., Treadway, M. T., Leonard, C. V., Kertz, S. J., &amp; Björgvinsson, T. (2016). Network analysis of depression and anxiety symptom relationships in a psychiatric sample. <em>Psychological Medicine</em>, <em>46</em>(16), 3359–3369. <a href="https://doi.org/10.1017/S0033291716002300">https://doi.org/10.1017/S0033291716002300</a></p>
</div>
<div id="ref-friedReplicability2018a">
<p>Fried, E. I., Eidhof, M. B., Palic, S., Costantini, G., Huisman-van Dijk, H. M., Bockting, C. L. H., Engelhard, I., Armour, C., Nielsen, A. B. S., &amp; Karstoft, K.-I. (2018). Replicability and Generalizability of Posttraumatic Stress Disorder (PTSD) Networks: A Cross-Cultural Multisite Study of PTSD Symptoms in Four Trauma Patient Samples. <em>Clinical Psychological Science</em>, <em>6</em>(3), 335–351. <a href="https://doi.org/10.1177/2167702617745092">https://doi.org/10.1177/2167702617745092</a></p>
</div>
</div>
</div>
