---
title: Prediction Intervals
subtitle: A frequentist's perspective
author: Josue Rodriguez
data: September 1st, 2024
format:
  html
---

```{r}
#| message: false

library(dplyr)
library(ggplot2)

theme_set(theme_minimal())
```


```{r}
x <- runif(1000, 0, 10)
y <- x + rnorm(1000)

model_1 <- lm(y ~ x)

get_pred <- function(x, model) {
  mod_coefs <- coef(model)
  yhat <- mod_coefs[1] + mod_coefs[2] * x
  return(yhat)
}


data_df <- data.frame(x, y)
```


```{r}

#' For every row in `df`, compute a rotated normal density
#' centered at `y` and shifted by `x`
compute_rotated_normal_densities <- function(x, model) {
  mu <- get_pred(x, model)
  sigma <- sigma(model)

  range <- mu + c(-3.2, 3.2) * sigma
  x_values <- seq(range[1], range[2], length.out = 100)
  densities <- dnorm(x_values, mean = mu, sd = sigma)

  rotated_densities_df <- tibble(
    x = densities + x - max(densities),
    y = x_values
  )

  return(rotated_densities_df)
}


all_densities_df  <- purrr::map_dfr(
  c(1, 3, 5, 7, 9),
  compute_rotated_normal_densities, 
  mod = model_1,
  .id = "id"
)
```

```{r}
#| fig-height: 8
#| fig-width: 10
#| fig-cap: y | x ~ N(y_hat, sigma_hat)
pred_interval_df <- tibble(x = 0:10)
pred_interval_df_95 <- bind_cols(
  pred_interval_df,
  predict(model_1, interval = "prediction", level = 0.95, newdata = pred_interval_df)
)

ggplot(data_df, aes(x, y)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = "lm", se = TRUE, lwd = 1, col = "forestgreen") +
  geom_path(data = all_densities_df, aes(group = id), lwd = 1, col = "steelblue") +
  # geom_polygon(data = all_densities_df, aes(y = scales::oob_squish(y, c(1, Inf)), group = id), lwd = 2) +
  geom_line(data = pred_interval_df_95, aes(x, lwr), lwd = 1, lty = 2, color = "tomato") +
  geom_line(data = pred_interval_df_95, aes(x, upr), lwd = 1, lty = 2, color = "tomato") 
```


